title: Safa Darwish
logo: Safa Darwish.jpeg
theme: jekyll-theme-minimal
description: >-
  Data Analyst | Power BI | SQL | Excel | Python | R
  Helping businesses make data-driven decisions with clear, compelling dashboards.
